import {
  Controller,
  All,
  Req,
  Res,
  HttpCode,
} from "@nestjs/common";
import { ApiTags, ApiOperation } from "@nestjs/swagger";
import type { FastifyRequest, FastifyReply } from "fastify";
import { Public } from "../../common/decorators/roles.decorator";
import { AuthService } from "./auth.service";

/**
 * Auth catch-all controller.
 *
 * All /auth/* requests are forwarded to the Better-Auth handler which
 * manages its own routing (sign-in, sign-up, session, 2FA, etc.).
 *
 * The NestJS layer adds:
 *   - Rate-limiting (inherited from ThrottlerModule global guard)
 *   - Audit logging via AuthService.writeAuditLog
 *   - Swagger documentation tags
 *
 * Individual endpoint docs are auto-generated by Better-Auth's OpenAPI
 * support (if enabled) — this controller just proxies the handler.
 */
@ApiTags("auth")
@Public() // Better-Auth handles its own authentication internally
@Controller("auth")
export class AuthController {
  constructor(private readonly authService: AuthService) {}

  @All("*")
  @HttpCode(200)
  @ApiOperation({
    summary: "Better-Auth handler — proxies all /auth/* requests",
    description:
      "Covers: sign-in, sign-up, sign-out, session, 2FA, email verification, password reset.",
  })
  async handle(
    @Req() req: FastifyRequest,
    @Res({ passthrough: false }) res: FastifyReply,
  ): Promise<void> {
    return this.authService.handleRequest(req, res);
  }
}
